# Generated by Django 5.2.1 on 2025-06-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectk', '0003_employee_alter_task_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='employeee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('salary', models.CharField()),
                ('address', models.TextField()),
            ],
        ),
    ]
