# Generated by Django 5.2.1 on 2025-05-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mask', '0002_laptop'),
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('brand', models.CharField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='laptop',
            name='age',
            field=models.CharField(),
        ),
    ]
