# Generated by Django 5.2.1 on 2025-05-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mask', '0004_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='email',
            field=models.EmailField(default=9961144690, max_length=254),
            preserve_default=False,
        ),
    ]
