# Generated by Django 5.2.1 on 2025-05-28 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mask', '0005_mobile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('des', models.TextField()),
                ('duration', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('course', models.CharField()),
                ('address', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Address2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.CharField()),
                ('location', models.CharField()),
                ('state', models.CharField()),
                ('district', models.CharField()),
                ('added', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mask.students')),
                ('add', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mask.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('roll_no', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mask.address2')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mask.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mask.teacher')),
            ],
        ),
    ]
