# Generated by Django 5.2.1 on 2025-06-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mask', '0009_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
