# Generated by Django 5.2.1 on 2025-06-29 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mask', '0011_expenses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_Name', models.CharField(max_length=100)),
                ('Description', models.TextField(max_length=200)),
                ('Task_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
