# Generated by Django 5.2.1 on 2025-07-06 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mask', '0017_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='bookingtime',
        ),
    ]
